// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdexapxvljamxrldsyln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkZXhhcHh2bGphbXhybGRzeWxuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2Mzg2OTMsImV4cCI6MjA2MDIxNDY5M30.ATxhEJdr5Y-TF0VBdY0MeR2Vmk6JmY1YDLQ2LPYZpV0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);